version: "3.8"

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: euler
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot_backend:
    build: .
    container_name: springboot_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/marketplace
      SPRING_DATASOURCE_USERNAME: euler
      SPRING_DATASOURCE_PASSWORD: senha123
    depends_on:
      - db
    ports:
      - "8081:8081"

volumes:
  postgres_data: